# Generated by Django 3.2.19 on 2024-02-21 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverychellan',
            name='balance',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
