# Generated by Django 3.2.19 on 2024-02-21 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0002_deliverychellan_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverychellan',
            name='to_inv',
            field=models.CharField(blank=True, default='Convert to invoice', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='deliverychellan',
            name='to_recinv',
            field=models.CharField(blank=True, default='Convert to reccuring invoice', max_length=100, null=True),
        ),
    ]
