# Generated by Django 3.2.19 on 2024-02-23 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0003_auto_20240221_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverychellan',
            name='reference',
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
    ]
