# Generated by Django 3.2.19 on 2024-03-28 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0004_alter_deliverychellan_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor_credits_bills',
            name='acc_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vendor_credits_bills',
            name='bill_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vendor_credits_bills',
            name='cheque',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vendor_credits_bills',
            name='payment_methode',
            field=models.CharField(blank=True, default='Cash', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vendor_credits_bills',
            name='status',
            field=models.CharField(default='Draft', max_length=100),
        ),
        migrations.AddField(
            model_name='vendor_credits_bills',
            name='upi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
