# Generated by Django 3.2.19 on 2024-04-01 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0005_auto_20240328_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor_credits_bills',
            name='balance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendor_credits_bills',
            name='paid',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendor_credits_bills',
            name='shipping_charge',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
