# Generated by Django 3.2.19 on 2024-04-08 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0006_auto_20240401_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverychellan',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='deliverychellan',
            name='gst_treatment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='deliverychellan',
            name='gstin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='deliverychellan',
            name='placeofsupply',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
